
@baseUrl = http://localhost:6000/api/v1/user

###
GET {{baseUrl}}?username=cibilex HTTP/1.1


###
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "username":"asdasd",
    "password":"cibilex",
    "permissions":3,
    "userType":1
}
